<?php
/**
 * Bingo Flashboard Display Window
 * This is a standalone display window showing the bingo board with all numbers
 * and highlighting called numbers. Designed for secondary monitor display.
 */

// Load configuration
include "config/settings.php";
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bingo Flashboard - <?= $setid; ?></title>
<link rel="stylesheet" href="include/flashboard.css">
<script src="include/flashboard.js" defer></script>
</head>
<body class="flashboard">

<div class="flashboard-container">
  <header class="flashboard-header">
    <h1 class="flashboard-title">🎱 BINGO FLASHBOARD</h1>
    <div class="set-id-display">Card Set: <?= htmlspecialchars($setid); ?></div>
  </header>

  <div class="flashboard-info">
    <div class="info-card">
      <div class="info-label">Current Number</div>
      <div class="info-value" id="current-number">---</div>
    </div>
    <div class="info-card">
      <div class="info-label">Winning Pattern</div>
      <div class="pattern-value" id="current-pattern">No pattern selected</div>
    </div>
  </div>

  <div class="bingo-board" id="bingo-board">
    <!-- Board will be generated by JavaScript -->
  </div>

  <div class="status-message">
    Connected to Bingo game. Numbers will appear automatically as they are drawn.
  </div>
</div>

</body>
</html>
